name: profile_app
description: A dynamic profile app with customizable UI.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.9.0
  dio: ^5.4.0
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  dartz: ^0.10.1
  image_picker: ^1.0.4
  provider: ^6.0.5
  go_router: ^12.1.1

  shared_preferences: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    
  fonts:
    - family: League Spartan
      fonts:
        - asset: assets/Fonts/LeagueSpartan-Thin.ttf
        - asset: assets/Fonts/Poppins-Italic.ttf
          weight: 500
        - asset: assets/Fonts/LeagueSpartan-Thin.ttf
          weight: 700
    